name: expressions

on:
  workflow_dispatch:

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: print a message
        run: echo "process is running"
        if: ${{ github.event_name == 'push' || github.ref == 'refs/head/main' }}
        #if: ${{ !contains(github.event.head_commit.message, 'WIP') }}
        #if: ${{ startsWith(github.ref, 'refs/tag/v') }}
    
