name: first WF

on:
  push:
    branches:
      - main

jobs:
  example-job: #job name
    runs-on: ubuntu-latest #runner
    
  steps:
    - name: print a welcome message
    run: echo"Welcome to our Github Actions WF"
    
    
  
