name: First WF

on:
  push:
    branches:
      - main

jobs:
  First-Job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 Print a welcome message
        run: echo "Welcome to our Github Actions WF"
      - name: Step 2 Checkout Repo
        uses: actions/checkout@v6.1.0
      - name: Step 3 List Repo files
        run: ls -la
    
    
  
